<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $number
     * @return \Doctrine\ORM\Query
     */
    public function getLastPost($number)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select('p.title, p.id, p.slug')
            ->orderBy('p.createdAt', 'desc')
            ->setMaxResults($number);
        return $qb->getQuery();
    }

    public function getNumberOfPostsByYear()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select('YEAR(p.createdAt) as yearPublished, COUNT(p.id) as numberOfPosts')
            ->groupBy('yearPublished')
            ->orderBy('yearPublished', 'DESC');
        return $qb->getQuery();
    }

    public function getPostsByYear($year)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select('p')
            ->where('YEAR(p.createdAt)=:year')
            ->orderBy('p.createdAt', 'DESC')
            ->setParameter('year', $year);
        return $qb->getQuery();
    }

}
