# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    #Test de la notion de service
    app.hello:
        class: AppBundle\Services\HelloService
        arguments:
          - "@security.token_storage"
        #tags:
        #  - {name: kernel.event_subscriber}

    doctrine.password:
        class: AppBundle\DoctrineListener\PasswordListener
        arguments:
          - "@security.password_encoder"
        tags:
          - {name: doctrine.event_listener, event: prePersist}


